### ISSUE TITLE
The 20200927 version have not network

### ISSUE THREAD

**Issue by Rexwei** [Virtual-Machines/Xubuntu-VirtualBox#3]

**Comment by DavidGarciaPrados** [comment]
Thank you, @Rexwei . Reverted to previous version.

**Comment by Rexwei** [comment]
> Thank you, @Rexwei . Reverted to previous version.

great! very good project!

**Comment by DavidGarciaPrados** [comment]
> > Thank you, @Rexwei . Reverted to previous version.
> 
> great! very good project!

I am happy to read that! I have updated again the machine. Now has BleachBit to keep it small.

**Comment by Rexwei** [comment]
> > > Thank you, @Rexwei . Reverted to previous version.
> > 
> > 
> > great! very good project!
> 
> I am happy to read that! I have updated again the machine. Now has BleachBit to keep it small.

Thans !Oh, that's amazing
