### ISSUE TITLE
locale component part missing

### ISSUE THREAD

**Issue by Rexwei** [Virtual-Machines/Xubuntu-VirtualBox#4]
hello!
if you want replace language and locale，run "sudo dpkg-reconfigre locale" after setting,tips some files are not found.
hope to fix it  :)

**Comment by DavidGarciaPrados** [comment]
Hello!
The command is "sudo dpkg-reconfigure locales"
You can run previously "sudo locale-gen" (example: "sudo locale-gen en_US en_US.UTF-8") to generate your desired locale.

More information here:
https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

**Comment by Rexwei** [comment]
OK! thank you !

**Comment by Rexwei** [comment]
> Hello, @Rexwei !
> The command is "sudo dpkg-reconfigure locales"
> You can run previously "sudo locale-gen" (example: "sudo locale-gen en_US en_US.UTF-8") to generate your desired locale.
> 
> More information here:
> https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

I found the problem

It is because bleachbit has the function of clearing useless languages that some language files are cleared

**Comment by DavidGarciaPrados** [comment]
> > Hello, @Rexwei !
> > The command is "sudo dpkg-reconfigure locales"
> > You can run previously "sudo locale-gen" (example: "sudo locale-gen en_US en_US.UTF-8") to generate your desired locale.
> > More information here:
> > https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue
> 
> I found the problem
> 
> It is because bleachbit has the function of clearing useless languages that some language files are cleared

Yes

**Comment by Rexwei** [comment]
> > > Hello, @Rexwei !
> > > The command is "sudo dpkg-reconfigure locales"
> > > You can run previously "sudo locale-gen" (example: "sudo locale-gen en_US en_US.UTF-8") to generate your desired locale.
> > > More information here:
> > > https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue
> > 
> > 
> > I found the problem
> > It is because bleachbit has the function of clearing useless languages that some language files are cleared
> 
> Yes

Now that the known problem originates from BleachBit,i still hope to change the language to my language ,so what file do i need to add??
![Screenshot_2020-10-14_19-49-17](https://user-images.githubusercontent.com/17174943/96027478-8388fa00-0e8a-11eb-9687-cdc86c6f69ed.png)
![Screenshot_2020-10-14_19-51-59](https://user-images.githubusercontent.com/17174943/96027487-87b51780-0e8a-11eb-8bdc-2f32f8b05bab.png)
