### ISSUE TITLE
Checksums displayed do not match the calculated </eom>

### ISSUE THREAD

**Issue by pedropedro** [Virtual-Machines/Xubuntu-VirtualBox#6]

**Comment by DavidGarciaPrados** [comment]
Thank you, @pedropedro 
I updated the checksum but did not upload the new OVA file. Sorry!
Solved!

**Comment by pedropedro** [comment]
Hmmm - you updated the hash / link (Integrity information:) to VirusTotal, where of course are the correct hashes. But the hashes *below* the link, i.e. in your project description, are still wrong. Example: SHA-256: 9d77a4c3d7ccd72f89bb5e4ddcec82de8886b1a483f2f8430aea470b5b90e6b1 is wrong.
My sugestion: remove the hashes from your page and just write: current checksums / hashes are on the VirusTotal site ... or something similar. Then you are on the safe side in the future ...
