### ISSUE TITLE
what is the root password for this ova

### ISSUE THREAD

**Issue by farhancode** [Virtual-Machines/Xubuntu-VirtualBox#8]
The root password for xubuntu virtualbox image is not provided.

![image](https://user-images.githubusercontent.com/48584133/160239165-2ea6bd7c-bd8b-4cbe-b3b8-b23b13a0b09f.png)

**Comment by DavidGarciaPrados** [comment]
> farhancode
The password is **xubuntu** as explained in Readme.md of this repository

**Comment by DavidGarciaPrados** [comment]
@farhancode The password is **xubuntu** as explained in Readme.md of this repository

**Comment by farhancode** [comment]
Thanks for the quick reply , I tried 'xubuntu' as password but it wasn't working.
Did a reinstall and it's working now.
